- 국가연구개발혁신법
- 국가연구개발혁신법 시행령
- 국가연구개발혁신법 시행규칙
- 과학기술분야 정부출연연구기관 등의 설립·운영 및 육성에 관한 법률
- 과학기술분야 정부출연연구기관 등의 설립·운영 및 육성에 관한 법률 시행령
- 공공기관의 운영에 관한 법률
- 공공기관의 운영에 관한 법률 시행령
- 국가를 당사자로 하는 계약에 관한 법률
- 국가를 당사자로 하는 계약에 관한 법률 시행령
- 공무원 여비 규정
